<script setup lang="ts">
import { computed, ref } from 'vue'
import { ArrowUpRight, ArrowDownLeft, Search, Phone, PhoneOutgoing, MessageSquareText, ShieldBan, Download, Disc3 } from '@lucide/vue'
import PageHeader from '../components/PageHeader.vue'
import { state } from '../state'
import { useRouter } from 'vue-router'
import type { Call } from '../types'
import { post } from '../api'
const q=ref(''),router=useRouter(),actionBusy=ref<Record<string,string>>({}),actionNotice=ref('')
const rows=computed(()=>state.snapshot?.calls.filter(c=>!q.value||c.number.includes(q.value)||c.displayName?.includes(q.value))||[])
const fmt=(v:string)=>new Intl.DateTimeFormat('zh-CN',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v))
const duration=(c:Call)=>{if(!c.connectedAt||!c.endedAt)return '';const seconds=Math.max(0,Math.round((new Date(c.endedAt).getTime()-new Date(c.connectedAt).getTime())/1000));return seconds>=60?`${Math.floor(seconds/60)}分${seconds%60}秒`:`${seconds}秒`}
const outcome=(c:Call)=>c.mediaOwner==='voicemail'?(c.connectedAt?`语音信箱 ${duration(c)}`:'语音信箱未接通'):c.connectedAt?`已通话 ${duration(c)}`:c.endReason==='rejected'?'已拒接':c.direction==='incoming'?'未接来电':c.state==='failed'?'呼叫失败':'未接通'
const blocked=(c:Call)=>!!state.snapshot?.rules.some(r=>r.enabled&&r.kind==='exact'&&r.pattern===c.number&&r.action==='block'&&(r.scope==='both'||r.scope==='call'))
async function dial(c:Call){actionBusy.value[c.id]='dial';actionNotice.value='';try{await post('/api/v1/calls',{number:c.number})}catch(e:any){actionNotice.value=`拨号失败：${e.code||e.message}`}finally{delete actionBusy.value[c.id]}}
function message(c:Call){router.push({path:'/messages',query:{number:c.number}})}
async function block(c:Call){if(blocked(c)||!confirm(`将 ${c.number} 加入电话与短信黑名单？`))return;actionBusy.value[c.id]='block';actionNotice.value='';try{await post('/api/v1/rules',{kind:'exact',pattern:c.number,label:'通话记录黑名单',category:'manual',action:'block',scope:'both',enabled:true});actionNotice.value=`已拉黑 ${c.number}`}catch(e:any){actionNotice.value=`拉黑失败：${e.code||e.message}`}finally{delete actionBusy.value[c.id]}}
</script>
<template><section><PageHeader eyebrow="电话" title="通话记录" description="所有呼入、呼出和未接来电。"><button class="primary compact" @click="router.push('/dial')"><Phone :size="16"/>拨号</button></PageHeader><p v-if="actionNotice" class="call-action-notice">{{actionNotice}}</p><article class="card table-card"><div class="toolbar"><label class="search"><Search/><input v-model="q" placeholder="搜索号码"/></label></div><div class="call-table"><div v-for="c in rows" :key="c.id" class="table-row"><span class="avatar">{{c.number.slice(-2)}}</span><div class="grow"><b>{{c.displayName||c.number}}</b><p><component :is="c.direction==='outgoing'?ArrowUpRight:ArrowDownLeft" :size="14"/> {{c.direction==='outgoing'?'呼出':'呼入'}}</p></div><span class="tag" :class="{active:!!c.connectedAt,failed:!c.connectedAt}">{{outcome(c)}}</span><time>{{fmt(c.startedAt)}}</time><div class="record-actions"><button title="拨出" aria-label="拨出" :disabled="!!actionBusy[c.id]" @click="dial(c)"><PhoneOutgoing/></button><button title="发送短信" aria-label="发送短信" @click="message(c)"><MessageSquareText/></button><button title="拉黑电话与短信" aria-label="拉黑电话与短信" :class="{blocked:blocked(c)}" :disabled="!!actionBusy[c.id]||blocked(c)" @click="block(c)"><ShieldBan/></button></div></div><p v-if="!rows.length" class="empty">没有匹配的通话</p></div></article><article v-if="state.snapshot?.recordings.length" class="card table-card recordings"><div class="card-head"><div><p class="eyebrow">音频档案</p><h2>通话录音</h2></div></div><div class="call-table"><div v-for="r in state.snapshot.recordings" :key="r.id" class="table-row"><span class="metric-icon violet"><Disc3/></span><div class="grow"><b>{{r.fileName}}</b><p>{{r.durationSeconds}} 秒 · {{Math.ceil(r.size/1024)}} KB</p></div><time>{{fmt(r.createdAt)}}</time><a class="icon-btn" :href="`/api/v1/recordings/${r.id}`" download><Download/></a></div></div></article></section></template>
