[general]
static=yes
writeprotect=yes
clearglobalvars=no

[from-groundwire]
exten => _X.,1,NoOp(Groundwire to cellular ${EXTEN})
 same => n,Dial(PJSIP/${EXTEN}@onsim,120)
 same => n,Hangup()
exten => _+X.,1,NoOp(Groundwire to cellular ${EXTEN})
 same => n,Dial(PJSIP/${EXTEN}@onsim,120)
 same => n,Hangup()

[from-onsim]
exten => 1001,1,NoOp(Cellular call to Groundwire)
 same => n,Dial(PJSIP/1001,45)
 same => n,Hangup()

[from-groundwire-message]
exten => _X.,1,NoOp(Groundwire SMS to cellular ${EXTEN})
 same => n,MessageSend(pjsip:onsim/sip:${EXTEN}@127.0.0.1:5062)
 same => n,Hangup()
exten => _+X.,1,NoOp(Groundwire SMS to cellular ${EXTEN})
 same => n,MessageSend(pjsip:onsim/sip:${EXTEN}@127.0.0.1:5062)
 same => n,Hangup()

[from-onsim-message]
exten => 1001,1,NoOp(Cellular SMS to Groundwire)
 same => n,MessageSend(pjsip:1001)
 same => n,Hangup()
